## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(app_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff =
application_types_to_replace = app_type_counts[app_type_counts < cutoff].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt_1 = classification_counts[classification_counts > 1]
print(classification_counts_gt_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < cutoff].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)

# Display the first few rows of the encoded DataFrame to check the result
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1)
y = application_df_encoded['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (27439, 50)
X_test shape: (6860, 50)
y_train shape: (27439,)
y_test shape: (6860,)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Display the shapes of the scaled datasets to confirm the scaling
print(f"X_train_scaled shape: {X_train_scaled.shape}")
print(f"X_test_scaled shape: {X_test_scaled.shape}")

X_train_scaled shape: (27439, 50)
X_test_scaled shape: (6860, 50)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_dim = X_train_scaled.shape[1]  # Number of features in the input layer

# Initialize the model
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation='relu', input_dim=input_dim))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 408

 dense_1 (Dense)             (None, 8)                 72

 dense_2 (Dense)             (None, 1)                 9

=================================================================
Total params: 489 (1.91 KB)
Trainable params: 489 (1.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(optimizer='adam',
           loss='binary_crossentropy',
           metrics=['accuracy'])

# Check that the model has been compiled correctly
print("Model compiled successfully!")

Model compiled successfully!

In [14]:
# Train the model
history = nn.fit(X_train_scaled,
                 y_train,
                 epochs=100,
                 batch_size=32,
                 validation_split=0.2,
                 verbose=1)

# Check that training is complete
print("Model training complete!")

Epoch 1/100
686/686 [==============================] - 5s 4ms/step - loss: 0.6045 - accuracy: 0.6983 - val_loss: 0.5598 - val_accuracy: 0.7340
Epoch 2/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5650 - accuracy: 0.7208 - val_loss: 0.5506 - val_accuracy: 0.7332
Epoch 3/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5576 - accuracy: 0.7253 - val_loss: 0.5479 - val_accuracy: 0.7369
Epoch 4/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5547 - accuracy: 0.7264 - val_loss: 0.5483 - val_accuracy: 0.7376
Epoch 5/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5531 - accuracy: 0.7268 - val_loss: 0.5464 - val_accuracy: 0.7358
Epoch 6/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7279 - val_loss: 0.5455 - val_accuracy: 0.7351
Epoch 7/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5511 - accuracy: 0.7275 - val_loss: 0.5448 - val_accuracy: 0.7358
Epoch 8/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5504 - accuracy: 0.7282 - val_loss: 0.5459 - val_accuracy: 0.7367
Epoch 9/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7286 - val_loss: 0.5462 - val_accuracy: 0.7345
Epoch 10/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5498 - accuracy: 0.7284 - val_loss: 0.5444 - val_accuracy: 0.7363
Epoch 11/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5491 - accuracy: 0.7289 - val_loss: 0.5441 - val_accuracy: 0.7371
Epoch 12/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7286 - val_loss: 0.5442 - val_accuracy: 0.7352
Epoch 13/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7302 - val_loss: 0.5469 - val_accuracy: 0.7365
Epoch 14/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5482 - accuracy: 0.7310 - val_loss: 0.5434 - val_accuracy: 0.7358
Epoch 15/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5480 - accuracy: 0.7309 - val_loss: 0.5448 - val_accuracy: 0.7363
Epoch 16/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5475 - accuracy: 0.7309 - val_loss: 0.5439 - val_accuracy: 0.7391
Epoch 17/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5475 - accuracy: 0.7309 - val_loss: 0.5428 - val_accuracy: 0.7362
Epoch 18/100
686/686 [==============================] - 2s 4ms/step - loss: 0.5472 - accuracy: 0.7307 - val_loss: 0.5444 - val_accuracy: 0.7374
Epoch 19/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7316 - val_loss: 0.5449 - val_accuracy: 0.7367
Epoch 20/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7312 - val_loss: 0.5440 - val_accuracy: 0.7341
Epoch 21/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7319 - val_loss: 0.5447 - val_accuracy: 0.7365
Epoch 22/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5468 - accuracy: 0.7315 - val_loss: 0.5452 - val_accuracy: 0.7363
Epoch 23/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7312 - val_loss: 0.5423 - val_accuracy: 0.7372
Epoch 24/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7312 - val_loss: 0.5421 - val_accuracy: 0.7363
Epoch 25/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7310 - val_loss: 0.5423 - val_accuracy: 0.7374
Epoch 26/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7314 - val_loss: 0.5416 - val_accuracy: 0.7391
Epoch 27/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7315 - val_loss: 0.5425 - val_accuracy: 0.7363
Epoch 28/100
686/686 [==============================] - 4s 5ms/step - loss: 0.5464 - accuracy: 0.7323 - val_loss: 0.5425 - val_accuracy: 0.7367
Epoch 29/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7315 - val_loss: 0.5424 - val_accuracy: 0.7385
Epoch 30/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7324 - val_loss: 0.5426 - val_accuracy: 0.7365
Epoch 31/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5463 - accuracy: 0.7317 - val_loss: 0.5432 - val_accuracy: 0.7356
Epoch 32/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7328 - val_loss: 0.5428 - val_accuracy: 0.7356
Epoch 33/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7335 - val_loss: 0.5435 - val_accuracy: 0.7383
Epoch 34/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5457 - accuracy: 0.7328 - val_loss: 0.5465 - val_accuracy: 0.7385
Epoch 35/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7320 - val_loss: 0.5429 - val_accuracy: 0.7371
Epoch 36/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7325 - val_loss: 0.5440 - val_accuracy: 0.7372
Epoch 37/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7329 - val_loss: 0.5435 - val_accuracy: 0.7356
Epoch 38/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7324 - val_loss: 0.5444 - val_accuracy: 0.7367
Epoch 39/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5456 - accuracy: 0.7331 - val_loss: 0.5429 - val_accuracy: 0.7363
Epoch 40/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5451 - accuracy: 0.7330 - val_loss: 0.5426 - val_accuracy: 0.7372
Epoch 41/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5451 - accuracy: 0.7322 - val_loss: 0.5442 - val_accuracy: 0.7371
Epoch 42/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5452 - accuracy: 0.7337 - val_loss: 0.5428 - val_accuracy: 0.7380
Epoch 43/100
686/686 [==============================] - 6s 8ms/step - loss: 0.5452 - accuracy: 0.7331 - val_loss: 0.5444 - val_accuracy: 0.7347
Epoch 44/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5454 - accuracy: 0.7331 - val_loss: 0.5431 - val_accuracy: 0.7376
Epoch 45/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5446 - accuracy: 0.7331 - val_loss: 0.5466 - val_accuracy: 0.7354
Epoch 46/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5449 - accuracy: 0.7328 - val_loss: 0.5438 - val_accuracy: 0.7369
Epoch 47/100
686/686 [==============================] - 5s 7ms/step - loss: 0.5449 - accuracy: 0.7332 - val_loss: 0.5433 - val_accuracy: 0.7347
Epoch 48/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5449 - accuracy: 0.7328 - val_loss: 0.5432 - val_accuracy: 0.7367
Epoch 49/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5449 - accuracy: 0.7327 - val_loss: 0.5435 - val_accuracy: 0.7356
Epoch 50/100
686/686 [==============================] - 5s 8ms/step - loss: 0.5444 - accuracy: 0.7333 - val_loss: 0.5435 - val_accuracy: 0.7378
Epoch 51/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5447 - accuracy: 0.7324 - val_loss: 0.5456 - val_accuracy: 0.7360
Epoch 52/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7334 - val_loss: 0.5443 - val_accuracy: 0.7371
Epoch 53/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7340 - val_loss: 0.5437 - val_accuracy: 0.7365
Epoch 54/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7333 - val_loss: 0.5441 - val_accuracy: 0.7360
Epoch 55/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5441 - accuracy: 0.7341 - val_loss: 0.5434 - val_accuracy: 0.7369
Epoch 56/100
686/686 [==============================] - 2s 4ms/step - loss: 0.5445 - accuracy: 0.7342 - val_loss: 0.5432 - val_accuracy: 0.7371
Epoch 57/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7328 - val_loss: 0.5446 - val_accuracy: 0.7363
Epoch 58/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7341 - val_loss: 0.5446 - val_accuracy: 0.7358
Epoch 59/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7336 - val_loss: 0.5435 - val_accuracy: 0.7365
Epoch 60/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7338 - val_loss: 0.5444 - val_accuracy: 0.7345
Epoch 61/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5439 - accuracy: 0.7339 - val_loss: 0.5453 - val_accuracy: 0.7367
Epoch 62/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7344 - val_loss: 0.5440 - val_accuracy: 0.7363
Epoch 63/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7332 - val_loss: 0.5452 - val_accuracy: 0.7382
Epoch 64/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7343 - val_loss: 0.5445 - val_accuracy: 0.7371
Epoch 65/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7340 - val_loss: 0.5458 - val_accuracy: 0.7371
Epoch 66/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7352 - val_loss: 0.5441 - val_accuracy: 0.7363
Epoch 67/100
686/686 [==============================] - 4s 5ms/step - loss: 0.5440 - accuracy: 0.7344 - val_loss: 0.5437 - val_accuracy: 0.7367
Epoch 68/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7345 - val_loss: 0.5449 - val_accuracy: 0.7351
Epoch 69/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7339 - val_loss: 0.5446 - val_accuracy: 0.7362
Epoch 70/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7337 - val_loss: 0.5440 - val_accuracy: 0.7374
Epoch 71/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7347 - val_loss: 0.5441 - val_accuracy: 0.7365
Epoch 72/100
686/686 [==============================] - 2s 4ms/step - loss: 0.5437 - accuracy: 0.7343 - val_loss: 0.5441 - val_accuracy: 0.7371
Epoch 73/100
686/686 [==============================] - 4s 5ms/step - loss: 0.5434 - accuracy: 0.7346 - val_loss: 0.5449 - val_accuracy: 0.7378
Epoch 74/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7344 - val_loss: 0.5440 - val_accuracy: 0.7371
Epoch 75/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7346 - val_loss: 0.5446 - val_accuracy: 0.7360
Epoch 76/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7342 - val_loss: 0.5439 - val_accuracy: 0.7352
Epoch 77/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7350 - val_loss: 0.5432 - val_accuracy: 0.7392
Epoch 78/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5438 - accuracy: 0.7336 - val_loss: 0.5441 - val_accuracy: 0.7365
Epoch 79/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5435 - accuracy: 0.7343 - val_loss: 0.5453 - val_accuracy: 0.7376
Epoch 80/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7345 - val_loss: 0.5460 - val_accuracy: 0.7369
Epoch 81/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7342 - val_loss: 0.5436 - val_accuracy: 0.7374
Epoch 82/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7351 - val_loss: 0.5446 - val_accuracy: 0.7363
Epoch 83/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7338 - val_loss: 0.5450 - val_accuracy: 0.7363
Epoch 84/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5432 - accuracy: 0.7339 - val_loss: 0.5445 - val_accuracy: 0.7374
Epoch 85/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5432 - accuracy: 0.7351 - val_loss: 0.5435 - val_accuracy: 0.7371
Epoch 86/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7340 - val_loss: 0.5451 - val_accuracy: 0.7363
Epoch 87/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7351 - val_loss: 0.5446 - val_accuracy: 0.7378
Epoch 88/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7336 - val_loss: 0.5431 - val_accuracy: 0.7382
Epoch 89/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7345 - val_loss: 0.5445 - val_accuracy: 0.7360
Epoch 90/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5428 - accuracy: 0.7337 - val_loss: 0.5441 - val_accuracy: 0.7374
Epoch 91/100
686/686 [==============================] - 3s 4ms/step - loss: 0.5428 - accuracy: 0.7351 - val_loss: 0.5446 - val_accuracy: 0.7380
Epoch 92/100
686/686 [==============================] - 4s 6ms/step - loss: 0.5431 - accuracy: 0.7340 - val_loss: 0.5442 - val_accuracy: 0.7374
Epoch 93/100
686/686 [==============================] - 5s 7ms/step - loss: 0.5432 - accuracy: 0.7351 - val_loss: 0.5436 - val_accuracy: 0.7382
Epoch 94/100
686/686 [==============================] - 3s 5ms/step - loss: 0.5430 - accuracy: 0.7351 - val_loss: 0.5450 - val_accuracy: 0.7382
Epoch 95/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7349 - val_loss: 0.5435 - val_accuracy: 0.7382
Epoch 96/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7344 - val_loss: 0.5443 - val_accuracy: 0.7369
Epoch 97/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7345 - val_loss: 0.5441 - val_accuracy: 0.7385
Epoch 98/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7347 - val_loss: 0.5439 - val_accuracy: 0.7387
Epoch 99/100
686/686 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7352 - val_loss: 0.5449 - val_accuracy: 0.7362
Epoch 100/100
686/686 [==============================] - 4s 5ms/step - loss: 0.5426 - accuracy: 0.7355 - val_loss: 0.5453 - val_accuracy: 0.7372
Model training complete!

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Print the loss and accuracy
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5577 - accuracy: 0.7236 - 312ms/epoch - 1ms/step
Loss: 0.5576878190040588, Accuracy: 0.7236151695251465

In [16]:
# Export our model to an HDF5 file
nn.save('AlphabetSoupCharity.h5')

# Confirm that the model was saved
print("Model saved to AlphabetSoupCharity.h5")

Model saved to AlphabetSoupCharity.h5

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [17]:
# Load the model from the HDF5 file
loaded_model = tf.keras.models.load_model('AlphabetSoupCharity.h5')

# Print the model summary to inspect its architecture
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 408

 dense_1 (Dense)             (None, 8)                 72

 dense_2 (Dense)             (None, 1)                 9

=================================================================
Total params: 489 (1.91 KB)
Trainable params: 489 (1.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
import h5py

# Open the HDF5 file
with h5py.File('AlphabetSoupCharity.h5', 'r') as file:
    # List all root level object names (aka keys)
    print("Keys: %s" % file.keys())
    a_group_key = list(file.keys())[0]

    # Get the HDF5 group object for the first key
    group = file[a_group_key]

    # Print the keys of this group
    print("Group keys: %s" % group.keys())

    # Print the contents of each key
    for key in group.keys():
        print(f"{key}: {group[key]}")

Keys: <KeysViewHDF5 ['model_weights', 'optimizer_weights']>
Group keys: <KeysViewHDF5 ['dense', 'dense_1', 'dense_2', 'top_level_model_weights']>
dense: <HDF5 group "/model_weights/dense" (1 members)>
dense_1: <HDF5 group "/model_weights/dense_1" (1 members)>
dense_2: <HDF5 group "/model_weights/dense_2" (1 members)>
top_level_model_weights: <HDF5 group "/model_weights/top_level_model_weights" (0 members)>